### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Zengratul** [mobilemindtec/nativescript-background-task#1]
Hello,

I had problem with http background module in splitting chunks and uploading large file. I like your module very much.

However, I can't install it because of library problem. Can I use it in my project?!

Error is 404, 401 not found the library location.
compile('br.com.mobilemind.api:mobilemind-droid-util:1.4

Please help me,

Thank you,

**Comment by mobilemindtec** [comment]
Hi @Zengratul,

We've moved our maven repositories this week. Use:

```
        maven {
            url "http://nexus.mobilemind.com.br/repository/mobile-mind-m2"
        }
        maven {
            url "http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2"
        }
```

Let's update in the documentation.

**Comment by Zengratul** [comment]
Thank you for your reply, @mobilemindtec 

I installed and checked your demo and native java code but I couldn't use function postFiles.

I set API URL, File Src, and identifier = 1 to upload 1 file. I do not understand jsonkey in your code.

Please provide an example for me to know how to use. I will use your module to upload large file for my project. I have just made a demo with my server for you to check.

Replace file name and file size as your idea in file item.services.ts -> run code -> click get key button -> get location -> upload as my code.

Thank you,

**Comment by mobilemindtec** [comment]
@Zengratul  another things.. This week we implemented IOS version and we updated demo version to use all options supported of plugin . So we recommend with you look to last demo version.

thanks!

**Comment by Zengratul** [comment]
Thank you for your reply, @mobilemindtec

I checked your demo again, I knew your demo to run in iOS.

I tested postFiles() gets error in my Android. I am waiting for your great demo in Android.

You should change nativescript-db-orm in packages.json. I changed it to work on my local pc.

This is error when I use postFiles():

An uncaught Exception occurred on "AsyncTask #1" thread.
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lbr/com/mobilemind/api/security/key/Base64;
	at br.com.mobilemind.ns.task.HttpPostFileTask.doInBackground(HttpPostFileTask.java:100)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "br.com.mobilemind.api.security.key.Base64" on path: DexPathList[[zip file "/data/app/org.nativescript.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.demo-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 6 more
	Suppressed: java.lang.ClassNotFoundException: br.com.mobilemind.api.security.key.Base64
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 7 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by mobilemindtec** [comment]
Hi @Zengratul 

 ```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lbr/com/mobilemind/api/security/key/Base64;
```

You add this in app.gradle?

```
android {
	useLibrary 'org.apache.http.legacy'
}
dependencies{
  compile('br.com.mobilemind.api:mobilemind-droid-util:1.4', {
      exclude group: 'com.google.android', module: 'android'
      exclude group: 'com.google.android', module: 'support-v4'
      exclude group: 'br.com.mobilemind.api', module: 'mobilemind-utils'
  })
  compile 'br.com.mobilemind.api:mobilemind-utils:1.3'
}
` ``

`com/mobilemind/api/security/key/Base64` is part of mobilemind-utils

**Comment by Zengratul** [comment]
Hi @mobilemindtec,

I checked again, it's same your usage guide and I did it.

I saw you develop br.com.mobilemind.api:mobilemind-utils to version 1.5.

I tested many times, and it's not worked. Can you try to test my code sample https://drive.google.com/open?id=0B38nN3BuYikcbXlDTURwQUxNTFk  ?!

Thank you very much for reply,

**Comment by mobilemindtec** [comment]
Hi @Zengratul 

The sample code work for my. The only thing I changed was to set a value for `_this.location` that was null.

**Comment by Zengratul** [comment]
Hi @mobilemindtec ,

I added jsonKey, it may work. However I could not get callback response as below, so I think it's also have trouble to upload successfully.

I tested on your demo, it may not work with my server. It responded:
"status 1"

I am looking forward to json response as below:
{"desc":"","secure":0,"name":"Test.txt","size":3}

You can test api, upload on Postman.

Thank you for reply,

**Comment by mobilemindtec** [comment]
@Zengratul  show me your code, please.

**Comment by Zengratul** [comment]
Hi @mobilemindtec ,

In Http Background, I use response.getBodyAsString() to get response json as below:
{"desc":"","secure":0,"name":"Test.txt","size":3}

I tested many way but can not take json response, please check for me. Http Background and Postman works well for json response.

I have a question, can this plugin upload raw, or body field, base64??? Because, I must split chunks to upload, it may not have file URL to upload. That means I have to read and upload immediately, not write to anywhere. This is good for mobile performance.

This is my code which I try my best to get call json response, same as previous version.
https://drive.google.com/open?id=0B38nN3BuYikcdU5xMGNxQWhzNWM

**Comment by mobilemindtec** [comment]
Hi @Zengratul ,

About your code. The return no have `getBodyAsString` method. The return on `doneCallback` is a array with of HttpPostData, ios or android:

```
// android code
public class HttpPostData implements Serializable{
    public String identifier;
    public String fileSrc;
    public String jsonKey;
    public String result;
}
```
Field `result` store reponse content. So:
```
doneCallback: function (dataPostList) {
   for (var i in dataPostList) {
       var postData = dataPostList[i];
       var data = JSON.parse(postData.result);
       console.log(postData.result);
  }
}
```

Parse server result to json.

This plugin is made only post in disk files Base64 Gzip (optional).  But, It would not be difficult to implement in memory data.

**Comment by Zengratul** [comment]
Hi @mobilemindtec,

I tried your doneCallback, it's not worked.

Test with file Test.txt 3 bytes:
E/HttpPostFileFormDataTask(15406): SyntaxError: Unexpected token u in JSON at position 0                                E/HttpPostFileFormDataTask(15406): SyntaxError: Unexpected token u in JSON at position 0                                E/HttpPostFileFormDataTask(15406):      at com.tns.Runtime.callJSMethodNative(Native Method)                            E/HttpPostFileFormDataTask(15406):      at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)                E/HttpPostFileFormDataTask(15406):      at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)                          E/HttpPostFileFormDataTask(15406):      at com.tns.Runtime.callJSMethod(Runtime.java:1047)                              E/HttpPostFileFormDataTask(15406):      at com.tns.Runtime.callJSMethod(Runtime.java:1028)                              E/HttpPostFileFormDataTask(15406):      at com.tns.Runtime.callJSMethod(Runtime.java:1018)

Test with wmv file 10 mb:
"{\"statusCode\":-1,\"message\":\"sendto failed: ECONNRESET (Connection reset by peer)\"}"  

Test with jpg file 1.5 mb:
console.log ------> [Ljava.lang.Object;@2ead3a97                                                                                        E/HttpPostFileFormDataTask(18367): SyntaxError: Unexpected token u in JSON at position 0                                E/HttpPostFileFormDataTask(18367): SyntaxError: Unexpected token u in JSON at position 0                                E/HttpPostFileFormDataTask(18367):      at com.tns.Runtime.callJSMethodNative(Native Method)                            E/HttpPostFileFormDataTask(18367):      at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)                E/HttpPostFileFormDataTask(18367):      at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)                          E/HttpPostFileFormDataTask(18367):      at com.tns.Runtime.callJSMethod(Runtime.java:1047)                              E/HttpPostFileFormDataTask(18367):      at com.tns.Runtime.callJSMethod(Runtime.java:1028)                              E/HttpPostFileFormDataTask(18367):      at com.tns.Runtime.callJSMethod(Runtime.java:1018) 

I have never been successful in upload any files.

I don't know how to upload from memory. Exactly, it's my problem, I can't find any tutorial for this.
I can only convert file into base64.

Thank you for reply,

**Comment by mobilemindtec** [comment]
Hi @Zengratul 

I verify your example app one more  time. The server return:  (in `errorCallback`)
```
{"error":"FILE_SIZE_MISS_MATCH"}
```
I don't know what this server expected receive. I not found fshare API documentation. 

When I sended a file using postman not worked too. Worked when I set body raw text and set content = 123. If I set content = 1234 this error persist. 

I changed android's lib to set `Content-Length` but nothing happened. 

This plugin post files using json or form-urlencoded. The content file is stored in field `jsonKey` of post. The server should read content of field `jsonKey` to process file content, and not think tha received content is file content.

Which is in memory data type that you wanna post? If is image, you can get base64 directly with nativescript `ImageSource` to post.

**Comment by Zengratul** [comment]
Hi @mobilemindtec,

I send you API Postman document. Please import api & global api to your Postman.

Our server supports binary application/octetstream, you can send binary or raw.

Get key -> get upload location -> select binary file to upload.

I hope your plugin can post binary file octetstream.

https://drive.google.com/open?id=0B38nN3BuYikcZ3VuVTdPYUh2NnM

**Comment by mobilemindtec** [comment]
Hi @Zengratul,

I did try send a file with your postman configs, but not worked. I did create a file with content `0000000000` and set headers:

```
Content-Type:application/octet-stream
Content-Length:10
Content-Range:bytes 0-10/10
```
The server return `{"error":"FILE_SIZE_MISS_MATCH"}` to any post. I did too try change android lib from plugin, to post a file using  `application/octet-stream`, but the same error is returned. I don't know that is happend with this server. I'll soon send you the new code so you can test.

**Comment by Zengratul** [comment]
Hi @mobilemindtec,

Thank for your check, you only need to upload single first.

Add Content-Type:application/octet-stream is enough to upload. You can upload raw or binary file as my example below.

Please do not use Content-Length & Content-Range, it only use when upload multi part file.

![1](https://cloud.githubusercontent.com/assets/7825869/24345992/bf141bf0-12fc-11e7-92bf-46a1c8a16e62.gif)

Sincerely,

**Comment by mobilemindtec** [comment]
Hi @Zengratul,

See a new vesion: https://github.com/mobilemindtec/nativescript-background-task/blob/master/native-src/android/app/src/main/java/br/com/mobilemind/ns/task/HttpPostDataTask.java

You can test using `postData` method:

```
   BackgroundTask.postData({
    url: this.location, // api url
    items: [{       
      fileSrc: this.filepath, // file origin path
      identifier: 1, // identifier to result
    }],
    headers: [
      {"Content-Type": "application/octet-stream"}                     
    ],
    doneCallback: function(dataPostList) {
      console.log("post data ok");
      console.log(dataPostList[0].result);

    },
    errorCallback: function(error){
        console.log("error " + error);
    }
```

If you set `Content-Type: "application/octet-stream"` will be sent file content in body. It's only a test, so might have bugs.

**Comment by Zengratul** [comment]
Hi @mobilemindtec,

I checked your new code, it's not completed in upload.

Please send me if you have new demo, code or your test package.

Sincerely,

**Comment by mobilemindtec** [comment]
You update android lib?

**Comment by Zengratul** [comment]
Yes, I updated in folder native-src and test more again but it still does not worked.

Thank you for reply,

**Comment by mobilemindtec** [comment]
Hi @Zengratul , 

Make this test:

1. Clone this project
2. Enter in native-src/server-mock folder
3. Run `npm install` 
4. Run  `node bin/www`
5. Enter in demo folder
6. Change server host variable in `main-page.js` to your network ip
7. Run `tns platform add android`
8. Run `tns run android`
9. Go to option POST DATA
10. See server logs and post result in app alert

**Comment by Zengratul** [comment]
Hi @mobilemindtec,,

I use Node JS 7.8, but I could not use mock server. I go to server-mock folder npm i & npm start. It may be freeze any long time.

Thank you for your reply,
![1](https://cloud.githubusercontent.com/assets/7825869/24850331/cade9fac-1df9-11e7-866c-a10002410f74.jpg)

**Comment by mobilemindtec** [comment]
Hi @Zengratul,

That is how it is. Now open a new console, run nativescript app and see logs.

**Comment by mobilemindtec** [comment]
Hi @Zengratul,

Can I close this issue? You did it?

**Comment by Zengratul** [comment]
Yes, thank you for answer.  I still could not use ,so I converted my project to react native and use Fetch Blob.
