### ISSUE TITLE
Adding Headers to File Download

### ISSUE THREAD

**Issue by ohenepee** [mobilemindtec/nativescript-background-task#2]
Is there any way we could add specific headers when downloading files

**Comment by mobilemindtec** [comment]
Hi @ohenepee,

Did not have header add option, but we just added. In the Android version it is already working and soon we will implement it for IOS. Thanks for the question.

**Comment by ohenepee** [comment]
Okay, I'm leaving the issue open perhaps you can close it when the iOS version has been implemented

**Comment by mobilemindtec** [comment]
Ok, IOS implemented.
