### ISSUE TITLE
Existing Download Resume

### ISSUE THREAD

**Issue by ohenepee** [mobilemindtec/nativescript-background-task#3]
Will download resume if the file already exists, but its size is lesser than the response's `Content-Length` ?

**Comment by mobilemindtec** [comment]
Hi @ohenepee,

I didn't understand your question. If destination file already exists, it will be removed always. If that is not the issue, please explain the situation better.

**Comment by ohenepee** [comment]
So I understand that you intentionally remove the file if it exists (as you've stated above). We're both talking about literally the same thing, except that I deem it helpful (in the case of large files and unreliable networks) to allow resuming an existing file is only its size is lesser than the `Content-Length` in the response. Perhaps you should make this an option `{resumeExistingFile: boolean}`.

Imagine a user in a developing country where mobile networks are a pain (personal experience), if such a user has to download say a 500MB file on an intermittently disconnecting 3G network, the user might never ever finish downloading the file, b'cos the network would disconnect roughly every 10-30 mins... I mean there are countless scenarios. perhaps the option of resuming can allow the developer (like myself) to incorporate the resume functionality if the file already exists but is lesser in size

**Comment by mobilemindtec** [comment]
Hi @ohenepee,

Now I undestand. This plugin was made for our need, and has evolved according to the need of our projects. We do not think of all possibilities, and your question is very good. But in that case the server where the download is made must support this functionality, right? We did never implements partial download. To very large uploads, this plugin have split file option.

**Comment by ohenepee** [comment]
Yes, the server will support that... it's just a matter of checking the response headers for `Accept-Range`. If not available, then server doesn't support it so existing file can be deleted.

**Comment by mobilemindtec** [comment]
Ok, let's implement .. we just do not promise soon.

**Comment by mobilemindtec** [comment]
Hi @ohenepee,

Feature to partial download/resume is done. Update the plugin code and read the new documentation.

**Comment by ohenepee** [comment]
You're awesome! I can't believe there are no emojis in the mobile web version of github
