### ISSUE TITLE
Ios implementation of onPostFile

### ISSUE THREAD

**Issue by pascaloo7** [mobilemindtec/nativescript-background-task#8]
Hi,

First of all, very nice plugin. Nativescript was really missing something like this. 
Do you have plans to implement the onPostFile function for ios? For android it's already working fine.

Thanks

**Comment by mobilemindtec** [comment]
Hi @pascaloo7,

All features work in Android and IOS. If you have any problem with IOS version, can post here.

**Comment by pascaloo7** [comment]
I get an error on ios `BackgroundTask.postData is not a function` where on android it seems to be working fine. When I did find the function in the background-task.android.js but not in background-task.ios.js I figured it was not jet implemented on ios.

**Comment by mobilemindtec** [comment]
@pascaloo7,

The `postData` functionality is the same as` postFiles`. This `postData` function is incomplete and was just a test for another user and I just forgot to remove it. It would be a version that sends the data in parts, using `Content-Range`, but it was not even concluded for android.

So, you can use `postFiles` with same arguments.

**Comment by pascaloo7** [comment]
@mobilemindtec I don't think they are the same because it fails on android when I change it from `postData` to `postFiles`.

The difference (as far as I see it):
`postData` function is using `new br.com.mobilemind.ns.task.HttpPostDataTask(args.url, callback)` for the task. 

`postFiles` function is using `new br.com.mobilemind.ns.task.HttpPostFileFormDataTask(args.url, callback)` or `new br.com.mobilemind.ns.task.HttpPostFileTask(args.url, callback)` for the task.

**Comment by mobilemindtec** [comment]
The class is different, but the functionality is same. The problem is on `items`:

A item should be like this:

```
{
  identifier: "StringId", // need be a string
  fileSrc: "file name to post.mp4", 
  jsonKey: 'myKeyName', // is required
  data: {  
     foo: "foo",
     bar: "bar",
     fileName; "file.mp4"
  }
}
```

Post data created by plugin:

```
{
   myKeyName: "data content base64",
    foo: "foo",
    bar: "bar",
    fileName; "file.mp4"
}
```

**Comment by pascaloo7** [comment]
Ah thanks, I got it working now. My problem was solved by changing `formData: false` to `true` in the options. Thanks
